### ISSUE TITLE
Chatbot process dies frequently to error from node-xmpp

### ISSUE THREAD

**Issue by uxdiogenes** [cjoudrey/wobot#29]
Looks to be a result of the node-xmpp module:

```
/Users/dbrito/skynetwork/chat-bot/node_modules/wobot/node_modules/node-xmpp/lib/xmpp/session.js:127
  this.connection.send(stanza.root());
                              ^
TypeError: Object   has no method 'root'
    at Client.Session.send (/Users/dbrito/skynetwork/chat-bot/node_modules/wobot/node_modules/node-xmpp/lib/xmpp/session.js:127:30)
    at null.<anonymous> (/Users/dbrito/skynetwork/chat-bot/node_modules/wobot/lib/bot.js:66:19)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by uxdiogenes** [comment]
The problem is probably partially also due to the constructor setting the bot to disconnect on error.

**Comment by uxdiogenes** [comment]
Upon further investigation it looks like this code in bot.js:65 might be the problem, because `node-xmpp` `Session.prototyp.send()` seems to expect to be able to call `.root()` on what's passed in:

``` js
    this.keepalive = setInterval(function() {
      self.jabber.send(' ');
      self.emit('ping');
    }, 30000);
```
