### ISSUE TITLE
Removed from npm?

### ISSUE THREAD

**Issue by TheBrockEllis** [cjoudrey/wobot#36]
I just tried installing wobot on to my Raspberry Pi today to play around with a new bot I've been tinkering with and I can't seem to install wobot at all. I run: `npm install wobot` and it says `Error: failed to fetch from registry: wobot`.

Here is the whole command:

``` bash
pi@raspberrypi ~/Code/HipChatBot $ npm install wobot
npm http GET https://registry.npmjs.org/wobot

npm ERR! Error: failed to fetch from registry: wobot
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/Code/HipChatBot/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.11+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "wobot"
npm ERR! cwd /home/pi/Code/HipChatBot
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: wobot
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Code/HipChatBot/npm-debug.log
npm not ok
```

Anyone else seeing this or am I just crazy?

**Comment by jahed** [comment]
Working fine for me. Though dependancies seem to be incorrect but that's a different issue.

Since it's been a while, maybe it's been fixed?
